// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// APIError - An error occurred interacting with the API.
type APIError struct {
	Code     *string                 `json:"code,omitempty"`
	Message  *string                 `json:"message,omitempty"`
	Details  map[string]any          `json:"details,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &APIError{}

func (e *APIError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
