/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationAuthenticate } from "../../funcs/authenticationAuthenticate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.AuthenticateRequest$inboundSchema,
};

export const tool$authenticationAuthenticate: ToolDefinition<typeof args> = {
  name: "authentication-authenticate",
  description:
    `Authenticate with the API by providing a username and password.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await authenticationAuthenticate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
