/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { configurationSubscribeToWebhooks } from "../../funcs/configurationSubscribeToWebhooks.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: z.array(operations.RequestBody$inboundSchema),
};

export const tool$configurationSubscribeToWebhooks: ToolDefinition<
  typeof args
> = {
  name: "configuration-subscribe-to-webhooks",
  description: `Subscribe to webhooks.

Subscribe to webhooks.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await configurationSubscribeToWebhooks(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
