/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { drinksGetById } from "../../funcs/drinksGetById.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetDrinkRequest$inboundSchema,
};

export const tool$drinksGetById: ToolDefinition<typeof args> = {
  name: "drinks-get-by-id",
  description: `Get a drink.

Get a drink by product code. Only available when authenticated.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await drinksGetById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
