/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { drinksDelete } from "../../funcs/drinksDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteDrinkRequest$inboundSchema,
};

export const tool$drinksDelete: ToolDefinition<typeof args> = {
  name: "drinks-delete",
  description: `Delete a drink.

Delete a drink. Only available when authenticated.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await drinksDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
