/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ingredientsGet } from "../../funcs/ingredientsGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListIngredientsRequest$inboundSchema.optional(),
};

export const tool$ingredientsGet: ToolDefinition<typeof args> = {
  name: "ingredients-get",
  description: `Get a list of ingredients.

Get a list of ingredients, if authenticated this will include stock levels and product codes otherwise it will only include public information.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await ingredientsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
