/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ordersCreate } from "../../funcs/ordersCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateOrderRequest$inboundSchema,
};

export const tool$ordersCreate: ToolDefinition<typeof args> = {
  name: "orders-create",
  description: `Create an order.

Create an order for a drink.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await ordersCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
