// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"context"
	"mockserver/internal/logging"
	"mockserver/internal/tracking"
	"net/http"
)

// GeneratedHandlers returns all generated handlers.
func GeneratedHandlers(ctx context.Context, dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) []*GeneratedHandler {
	return []*GeneratedHandler{
		NewGeneratedHandler(ctx, http.MethodGet, "/drinks", pathGetDrinks(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/drinks/search", pathGetDrinksSearch(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/drinks/{productCode}", pathGetDrinksProductCode(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/ingredients", pathGetIngredients(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodPatch, "/drinks/{productCode}", pathPatchDrinksProductCode(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodPost, "/authenticate", pathPostAuthenticate(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodPost, "/order", pathPostOrder(dir, rt)),
	}
}
