// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package callbacks

import (
	"mockserver/internal/sdk/models/components"
)

type CreateOrderOrderUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// An unknown error occurred interacting with the API.
	Error *components.Error
}

func (o *CreateOrderOrderUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateOrderOrderUpdateResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

type CreateOrderOrderUpdateRequest struct {
	// An order for a drink or ingredient.
	Order *components.OrderInput `json:"order,omitempty"`
}

func (o *CreateOrderOrderUpdateRequest) GetOrder() *components.OrderInput {
	if o == nil {
		return nil
	}
	return o.Order
}
