/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { SpeakeasyBar } from "../index.js";
import { AuthenticateResponseBody } from "../models/operations/index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Authentication Authenticate", async () => {
  const testHttpClient = createTestHTTPClient("authenticate");

  const speakeasyBar = new SpeakeasyBar({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
  });

  const result = await speakeasyBar.authentication.authenticate({});
  expect(result).toBeDefined();
  expect(result as AuthenticateResponseBody).toEqual({});
});
