/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { SpeakeasyBar } from "../index.js";
import { Ingredient } from "../models/index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Ingredients List Ingredients", async () => {
  const testHttpClient = createTestHTTPClient("listIngredients");

  const speakeasyBar = new SpeakeasyBar({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: process.env["SPEAKEASYBAR_API_KEY"] ?? "value",
  });

  const result = await speakeasyBar.ingredients.get();
  expect(result).toBeDefined();
  expect(result as Ingredient[]).toEqual([
    {
      name: "Sugar Syrup",
      type: "packaged",
      stock: 10,
      productCode: "AC-A2DF3",
      photo: "https://speakeasy.bar/ingredients/sugar_syrup.jpg",
    },
  ]);
});
