/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { SpeakeasyBar } from "../index.js";
import { CreateOrderResponseBody } from "../models/operations/index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Orders Create Order Pending Order", async () => {
  const testHttpClient = createTestHTTPClient("createOrder-pending_order");

  const speakeasyBar = new SpeakeasyBar({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: process.env["SPEAKEASYBAR_API_KEY"] ?? "value",
  });

  const result = await speakeasyBar.orders.create({
    requestBody: {
      orderType: "drink",
      productCode: "AC-A2DF3",
      quantity: 185162,
    },
  });
  expect(result).toBeDefined();
  expect(result as CreateOrderResponseBody).toEqual({
    orderType: "ingredient",
    productCode: "AC-A2DF3",
    quantity: 924003,
    status: "pending",
  });
});

test("Orders Create Order Completed Order", async () => {
  const testHttpClient = createTestHTTPClient("createOrder-completed_order");

  const speakeasyBar = new SpeakeasyBar({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: process.env["SPEAKEASYBAR_API_KEY"] ?? "value",
  });

  const result = await speakeasyBar.orders.create({
    requestBody: {
      orderType: "drink",
      productCode: "AC-A2DF3",
      quantity: 887049,
    },
  });
  expect(result).toBeDefined();
  expect(result as CreateOrderResponseBody).toEqual({
    orderType: "drink",
    productCode: "AC-A2DF3",
    quantity: 852070,
    status: "processing",
  });
});

test("Orders Create Order", async () => {
  const testHttpClient = createTestHTTPClient("createOrder");

  const speakeasyBar = new SpeakeasyBar({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: process.env["SPEAKEASYBAR_API_KEY"] ?? "value",
  });

  const result = await speakeasyBar.orders.create({
    requestBody: {
      orderType: "ingredient",
      productCode: "AC-A2DF3",
      quantity: 127985,
    },
  });
  expect(result).toBeDefined();
  expect(result as CreateOrderResponseBody).toEqual({
    orderType: "drink",
    productCode: "AC-A2DF3",
    quantity: 988377,
    status: "complete",
  });
});
