/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { configurationSubscribeToWebhooks } from "../funcs/configurationSubscribeToWebhooks.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Configuration extends ClientSDK {
  /**
   * Subscribe to webhooks.
   *
   * @remarks
   * Subscribe to webhooks.
   */
  async subscribeToWebhooks(
    request: Array<operations.RequestBody>,
    options?: RequestOptions,
  ): Promise<models.ErrorT | undefined> {
    return unwrapAsync(configurationSubscribeToWebhooks(
      this,
      request,
      options,
    ));
  }
}
