/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { CreateAcceptEnum, ordersCreate } from "../funcs/ordersCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { CreateAcceptEnum } from "../funcs/ordersCreate.js";

export class Orders extends ClientSDK {
  /**
   * Create an order.
   *
   * @remarks
   * Create an order for a drink.
   */
  async create(
    request: operations.CreateOrderRequest,
    options?: RequestOptions & { acceptHeaderOverride?: CreateAcceptEnum },
  ): Promise<operations.CreateOrderResponse> {
    return unwrapAsync(ordersCreate(
      this,
      request,
      options,
    ));
  }
}
