// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type AuthenticateRequest struct {
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
}

func (o *AuthenticateRequest) GetUsername() *string {
	if o == nil {
		return nil
	}
	return o.Username
}

func (o *AuthenticateRequest) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

// AuthenticateResponseBody - The api key to use for authenticated endpoints.
type AuthenticateResponseBody struct {
	Token *string `json:"token,omitempty"`
}

func (o *AuthenticateResponseBody) GetToken() *string {
	if o == nil {
		return nil
	}
	return o.Token
}

type AuthenticateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The api key to use for authenticated endpoints.
	Object *AuthenticateResponseBody
	// An unknown error occurred interacting with the API.
	Error *components.Error
}

func (o *AuthenticateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AuthenticateResponse) GetObject() *AuthenticateResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *AuthenticateResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
