// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteDrinkRequest struct {
	ProductCode string `pathParam:"style=simple,explode=false,name=productCode"`
}

func (o *DeleteDrinkRequest) GetProductCode() string {
	if o == nil {
		return ""
	}
	return o.ProductCode
}

type DeleteDrinkResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// An unknown error occurred interacting with the API.
	Error *components.Error
}

func (o *DeleteDrinkResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteDrinkResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
