// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetDrinkRequest struct {
	ProductCode string `pathParam:"style=simple,explode=false,name=productCode"`
}

func (o *GetDrinkRequest) GetProductCode() string {
	if o == nil {
		return ""
	}
	return o.ProductCode
}

type GetDrinkResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A drink.
	Drink *components.Drink
	// An unknown error occurred interacting with the API.
	Error   *components.Error
	Headers map[string][]string
}

func (o *GetDrinkResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetDrinkResponse) GetDrink() *components.Drink {
	if o == nil {
		return nil
	}
	return o.Drink
}

func (o *GetDrinkResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *GetDrinkResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
