// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DrinkIngredient struct {
}

type ListIngredientsRequest struct {
	// A list of ingredients to filter by. If not provided all ingredients will be returned.
	Ingredients []string `queryParam:"style=form,explode=false,name=ingredients"`
	// A list of drink ingredients to filter by. If not provided all ingredients will be returned.
	DrinkIngredients []DrinkIngredient `queryParam:"style=form,explode=false,name=drinkIngredients"`
}

func (o *ListIngredientsRequest) GetIngredients() []string {
	if o == nil {
		return nil
	}
	return o.Ingredients
}

func (o *ListIngredientsRequest) GetDrinkIngredients() []DrinkIngredient {
	if o == nil {
		return nil
	}
	return o.DrinkIngredients
}

type ListIngredientsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of ingredients.
	Ingredients []components.Ingredient
	// An unknown error occurred interacting with the API.
	Error *components.Error
}

func (o *ListIngredientsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListIngredientsResponse) GetIngredients() []components.Ingredient {
	if o == nil {
		return nil
	}
	return o.Ingredients
}

func (o *ListIngredientsResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
