// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
)

type Webhook string

const (
	WebhookStockUpdate Webhook = "stockUpdate"
)

func (e Webhook) ToPointer() *Webhook {
	return &e
}
func (e *Webhook) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "stockUpdate":
		*e = Webhook(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Webhook: %v", v)
	}
}

type RequestBody struct {
	URL     *string  `json:"url,omitempty"`
	Webhook *Webhook `json:"webhook,omitempty"`
}

func (o *RequestBody) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

func (o *RequestBody) GetWebhook() *Webhook {
	if o == nil {
		return nil
	}
	return o.Webhook
}

type SubscribeToWebhooksResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// An unknown error occurred interacting with the API.
	Error *components.Error
}

func (o *SubscribeToWebhooksResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SubscribeToWebhooksResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
