// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"io"
	"mockserver/internal/sdk/models/components"
)

type UpdateDrinkRawRequest struct {
	ProductCode string    `pathParam:"style=simple,explode=false,name=productCode"`
	Drink       io.Reader `request:"mediaType=text/csv"`
}

func (o *UpdateDrinkRawRequest) GetProductCode() string {
	if o == nil {
		return ""
	}
	return o.ProductCode
}

func (o *UpdateDrinkRawRequest) GetDrink() io.Reader {
	if o == nil {
		return nil
	}
	return o.Drink
}

type UpdateDrinkRawResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The drink was updated successfully.
	Drink *components.Drink
	Body  []byte
	// An unknown error occurred interacting with the API.
	Error *components.Error
}

func (o *UpdateDrinkRawResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateDrinkRawResponse) GetDrink() *components.Drink {
	if o == nil {
		return nil
	}
	return o.Drink
}

func (o *UpdateDrinkRawResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *UpdateDrinkRawResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
