// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateDrinkStringRequest struct {
	ProductCode string `pathParam:"style=simple,explode=false,name=productCode"`
	RequestBody string `request:"mediaType=text/*"`
}

func (o *UpdateDrinkStringRequest) GetProductCode() string {
	if o == nil {
		return ""
	}
	return o.ProductCode
}

func (o *UpdateDrinkStringRequest) GetRequestBody() string {
	if o == nil {
		return ""
	}
	return o.RequestBody
}

type UpdateDrinkStringResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The drink was updated successfully.
	Drink *components.Drink
	Body  []byte
	// An unknown error occurred interacting with the API.
	Error *components.Error
}

func (o *UpdateDrinkStringResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateDrinkStringResponse) GetDrink() *components.Drink {
	if o == nil {
		return nil
	}
	return o.Drink
}

func (o *UpdateDrinkStringResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *UpdateDrinkStringResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
