/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Example usage of the speakeasy-bar SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx authenticationAuthenticate.ts
 */

import { SpeakeasyBar } from "speakeasy-bar";

const speakeasyBar = new SpeakeasyBar();

async function main() {
  const result = await speakeasyBar.authenticate({});

  console.log(result);
}

main().catch(console.error);
