/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteDrinkRequest = {
  productCode: string;
};

/** @internal */
export const DeleteDrinkRequest$inboundSchema: z.ZodType<
  DeleteDrinkRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  productCode: z.string(),
});

/** @internal */
export type DeleteDrinkRequest$Outbound = {
  productCode: string;
};

/** @internal */
export const DeleteDrinkRequest$outboundSchema: z.ZodType<
  DeleteDrinkRequest$Outbound,
  z.ZodTypeDef,
  DeleteDrinkRequest
> = z.object({
  productCode: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteDrinkRequest$ {
  /** @deprecated use `DeleteDrinkRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteDrinkRequest$inboundSchema;
  /** @deprecated use `DeleteDrinkRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteDrinkRequest$outboundSchema;
  /** @deprecated use `DeleteDrinkRequest$Outbound` instead. */
  export type Outbound = DeleteDrinkRequest$Outbound;
}

export function deleteDrinkRequestToJSON(
  deleteDrinkRequest: DeleteDrinkRequest,
): string {
  return JSON.stringify(
    DeleteDrinkRequest$outboundSchema.parse(deleteDrinkRequest),
  );
}

export function deleteDrinkRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteDrinkRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteDrinkRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteDrinkRequest' from JSON`,
  );
}
