// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package webhooks

import (
	"mockserver/internal/sdk/models/components"
)

type StockUpdateRequest struct {
	Drink      *components.DrinkInput      `json:"drink,omitempty"`
	Ingredient *components.IngredientInput `json:"ingredient,omitempty"`
}

func (o *StockUpdateRequest) GetDrink() *components.DrinkInput {
	if o == nil {
		return nil
	}
	return o.Drink
}

func (o *StockUpdateRequest) GetIngredient() *components.IngredientInput {
	if o == nil {
		return nil
	}
	return o.Ingredient
}

type StockUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// An unknown error occurred interacting with the API.
	Error *components.Error
}

func (o *StockUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *StockUpdateResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
