// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DrinkIngredient - An ingredient required to make a drink.
type DrinkIngredient struct {
	// The product code of an ingredient, only available when authenticated.
	IngredientProductCode string `json:"ingredientProductCode"`
	// The number of units of the ingredient required to make the drink.
	Quantity int64 `json:"quantity"`
}

func (o *DrinkIngredient) GetIngredientProductCode() string {
	if o == nil {
		return ""
	}
	return o.IngredientProductCode
}

func (o *DrinkIngredient) GetQuantity() int64 {
	if o == nil {
		return 0
	}
	return o.Quantity
}
