// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// DrinkDataLevel - The level of data included in the response.
type DrinkDataLevel string

const (
	DrinkDataLevelAuthenticated DrinkDataLevel = "authenticated"
)

func (e DrinkDataLevel) ToPointer() *DrinkDataLevel {
	return &e
}
func (e *DrinkDataLevel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "authenticated":
		*e = DrinkDataLevel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DrinkDataLevel: %v", v)
	}
}

type Drink struct {
	// The name of the drink.
	Name string `json:"name"`
	// The type of drink.
	Type *DrinkType `json:"type,omitempty"`
	// The price of one unit of the drink in US cents.
	Price float64 `json:"price"`
	// A photo of the drink.
	Photo *string `json:"photo,omitempty"`
	// The level of data included in the response.
	DataLevel *DrinkDataLevel `json:"dataLevel,omitempty"`
	// The number of units of the drink in stock, only available when authenticated.
	Stock *int64 `json:"stock,omitempty"`
	// The product code of a drink, only available when authenticated.
	ProductCode string `json:"productCode"`
	// The ingredients required to make the drink, only available when authenticated.
	Ingredients []DrinkIngredient `json:"ingredients,omitempty"`
}

func (o *Drink) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Drink) GetType() *DrinkType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *Drink) GetPrice() float64 {
	if o == nil {
		return 0.0
	}
	return o.Price
}

func (o *Drink) GetPhoto() *string {
	if o == nil {
		return nil
	}
	return o.Photo
}

func (o *Drink) GetDataLevel() *DrinkDataLevel {
	if o == nil {
		return nil
	}
	return o.DataLevel
}

func (o *Drink) GetStock() *int64 {
	if o == nil {
		return nil
	}
	return o.Stock
}

func (o *Drink) GetProductCode() string {
	if o == nil {
		return ""
	}
	return o.ProductCode
}

func (o *Drink) GetIngredients() []DrinkIngredient {
	if o == nil {
		return nil
	}
	return o.Ingredients
}
