// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DrinkInput struct {
	// The name of the drink.
	Name string `json:"name"`
	// The type of drink.
	Type *DrinkType `json:"type,omitempty"`
	// The price of one unit of the drink in US cents.
	Price float64 `json:"price"`
	// A photo of the drink.
	Photo *string `json:"photo,omitempty"`
	// The product code of a drink, only available when authenticated.
	ProductCode string `json:"productCode"`
	// The ingredients required to make the drink, only available when authenticated.
	Ingredients []DrinkIngredient `json:"ingredients,omitempty"`
}

func (o *DrinkInput) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *DrinkInput) GetType() *DrinkType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *DrinkInput) GetPrice() float64 {
	if o == nil {
		return 0.0
	}
	return o.Price
}

func (o *DrinkInput) GetPhoto() *string {
	if o == nil {
		return nil
	}
	return o.Photo
}

func (o *DrinkInput) GetProductCode() string {
	if o == nil {
		return ""
	}
	return o.ProductCode
}

func (o *DrinkInput) GetIngredients() []DrinkIngredient {
	if o == nil {
		return nil
	}
	return o.Ingredients
}
