/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The type of drink.
 */
export const DrinkType = {
  Cocktail: "cocktail",
  NonAlcoholic: "non-alcoholic",
  Beer: "beer",
  Wine: "wine",
  Spirit: "spirit",
  Other: "other",
} as const;
/**
 * The type of drink.
 */
export type DrinkType = ClosedEnum<typeof DrinkType>;

/** @internal */
export const DrinkType$inboundSchema: z.ZodNativeEnum<typeof DrinkType> = z
  .nativeEnum(DrinkType);

/** @internal */
export const DrinkType$outboundSchema: z.ZodNativeEnum<typeof DrinkType> =
  DrinkType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DrinkType$ {
  /** @deprecated use `DrinkType$inboundSchema` instead. */
  export const inboundSchema = DrinkType$inboundSchema;
  /** @deprecated use `DrinkType$outboundSchema` instead. */
  export const outboundSchema = DrinkType$outboundSchema;
}
