/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The type of ingredient.
 */
export const IngredientType = {
  Fresh: "fresh",
  LongLife: "long-life",
  Packaged: "packaged",
} as const;
/**
 * The type of ingredient.
 */
export type IngredientType = ClosedEnum<typeof IngredientType>;

/** @internal */
export const IngredientType$inboundSchema: z.ZodNativeEnum<
  typeof IngredientType
> = z.nativeEnum(IngredientType);

/** @internal */
export const IngredientType$outboundSchema: z.ZodNativeEnum<
  typeof IngredientType
> = IngredientType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IngredientType$ {
  /** @deprecated use `IngredientType$inboundSchema` instead. */
  export const inboundSchema = IngredientType$inboundSchema;
  /** @deprecated use `IngredientType$outboundSchema` instead. */
  export const outboundSchema = IngredientType$outboundSchema;
}
